[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/ryanuber/go-glob"
  version = "0.1.0"

[[constraint]]
  name = "github.com/ogier/pflag"
  version = "0.0.1"
